# SPDX-License-Identifier: Apache-2.0
[package]
name = "ta"
version = "0.1.0"
authors = ["The ta-rzv2l-rs authors"]
license = "Apache-2.0"
description = "signer OP-TEE Trusted Application (ECDSA P-256 device signer)."
edition = "2021"

[dependencies]
proto = { path = "../proto" }
optee-utee = { path = "../../third_party/teaclave-trustzone-sdk/optee-utee", default-features = false }
optee-utee-sys = { path = "../../third_party/teaclave-trustzone-sdk/optee-utee/optee-utee-sys", default-features = false }

[build-dependencies]
proto = { path = "../proto" }
optee-utee-build = { path = "../../third_party/teaclave-trustzone-sdk/optee-utee-build" }

[profile.release]
panic = "abort"
lto = true
opt-level = 1
